// import { Inter } from 'next/font/google'

// import localFont from 'next/font/local'

import Nav from "../components/Nav"
import Footer from "../components/Footer"

import "../styles/main.css"
import "../styles/md.css"
import "../styles/prism-one-dark.css"

// const helveticaNeue = localFont({
//   src: [

//   ]
// })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <Nav />
          <div className="container mx-auto grow">
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  )
}
